version: "3.8"

services:
  app:
    build:
      context: ../../MyParser
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vacancies
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mynet
    volumes:
      - m2-cache:/root/.m2

volumes:
  m2-cache:

networks:
  mynet:
    external: true